export {default as  CompanyInfoFirstRow} from './Header/CompanyInfoFirstRow'
export {default as  TabMenu} from './TabMenu'
export {default as  CompanyInfoRowTwo} from './Header/CompanyInfoRowTwo'
export {default as  Header} from './Header/Header'
export {default as  TotalAreas} from './TotalAreas/TotalAreas'